### ISSUE TITLE
Help icon: 'coming soon'

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/untd-map#32]
From our call earlier today - Help copy is outdated so for the Feb 26 demo, add a "coming soon" message instead

**Comment by amygroshek** [comment]
@laurendoone I edited this copy to remove the previous disd schools text. It's pretty boilerplate. I think we're fine leaving it enabled with the revised info. Staged at https://hyperobjekt.github.io/untd-map/#/
