### ISSUE TITLE
Tour icon: hide or 'coming soon'

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/untd-map#33]
From our call earlier today - the Tour is outdated so for the Feb 26 demo, either hide the icon or add "coming soon" message

**Comment by laurendoone** [comment]
@lougroshek oops yes sorry! i transferred it over to untd-map now

**Comment by amygroshek** [comment]
Hidden. Staged at https://hyperobjekt.github.io/untd-map/#
