### ISSUE TITLE
Revise tour for mobile and desktop

### ISSUE THREAD

**Issue by amygroshek** [Hyperobjekt/untd-map#38]

**Comment by touchRED** [comment]
@laurendoone tour script:

1. [Display map view] In the map view, geographic entities are displayed and colored according to where they fall in the currently selected metric. On hover, a tooltip provides more information about regions as well as point features on the map. 
2. [Highlight controls]  Use these controls to zoom in and out, take a screenshot of the map, and reset the map.
3. [Highlight legend] The map legend shows which intervals of the currently selected metric are toggled on or off. 
4. [Highlight metrics panel] Use the metrics panel to customize which geographic entities are displayed on the map along with the active metric.
5. [Highlight entities dropdown] Use the dropdown to switch between different types of regions like zip codes, census tracts, and so on.
6. [Highlight an indicator] Click a metric to toggle certain intervals on or off.
7. [Highlight features panel] Click checkboxes within the features panel to toggle different types of features on or off.
8. [Highlight search bar] Search for a location using the search bar. When selecting a location, the map will zoom and pan to center this location in the viewport. 
9. [Highlight share button] Use the share menu to distribute the explorer on social media, via email, or embed. 
10. [Highlight info panel button] The info panel contains additional information about the interface and its use.
11. [Highlight “repeat tour” button] If necessary, click the “repeat tour” button to display this information again.

**Comment by laurendoone** [comment]
@touchRED is this one done?
