### ISSUE TITLE
Map: styling updates

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/untd-map#42]
Feedback from client:
- The individual point icons that are just the icon with no circle or outline can be hard to see on the map. 
- Map is hard to read - maybe due to polygon outlines?

TO DO:

- [ ] Make the point icons a bit darker so they stand out on the map
- [ ] Make the map colors more translucent
- [x] Play around with removing the census tract stroke altogether, or make it match the fill color. To differentiate between two census tracts with the same fill color, maybe highlight the tract when hovering on it?

**Comment by amygroshek** [comment]
@laurendoone These are not simple styling updates. They require replacing the icons or changing several map layers. 

Sasha and I adjusted the census tract fill and border yesterday, so that item can be removed.
