### ISSUE TITLE
New icon: college

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/untd-map#47]
The client will be adding a new point feature to the explorer map for colleges and requested a new icon (graduation cap). Can you design this icon so we can add to the map?

**Comment by amygroshek** [comment]
@sashasashasasha @elianakm Did we end up creating this icon? I do see that the client added a `highed` point type for college campuses.

**Comment by sashasashasasha** [comment]
@lougroshek The icon is in [Figma](https://www.figma.com/file/Xxu6JB55X7j77cGahUmqWO/UNTD-Mockups-and-Wireframes?node-id=896%3A17) in the page Icons. 

Let me know once you have implemented it and I can see if it needs any tweaks

**Comment by amygroshek** [comment]
I have added this icon, and updated the icon hierarchy to display it even though everything else displayed in that category has a subcategory. However, the client has no `highed` point features in their point feature set. I have created an issue about it in their repo. https://github.com/childpovertyactionlab/Social-Mobility/issues/4
