### ISSUE TITLE
Form for data revision suggestions

### ISSUE THREAD

**Issue by amygroshek** [Hyperobjekt/untd-map#6]
Create a form component, which allows user to submit comments/revision suggestions.
- [x] Form in modal dialog
- [x] Launched from: geo feature slideout panel, control panel button, or clicking on a point feature
- [x] If the form is opened from geo feature, form is pre-populated with that information
- [x] If the form is opened from point feature click, form is pre-populated with that information
- [x] If the form is opened from button click, option to use current location (if geolocation is enabled in the browser) or option to use geocoding api to search for a poi or address
- [x] Submits to a netlify form
- [x] Display submission progress and success/completion or error

**Comment by laurendoone** [comment]
@lougroshek do you know if this needs to be done for the feb 26 demo?

**Comment by amygroshek** [comment]
No, I don't know.
